# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: janderland
author: Jon Anderson

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://jander.land
root: /
permalink: :title/

# Directory
source_dir: source
public_dir: public
tag_dir: tags
code_dir: downloads/code

# Writing
post_asset_folder: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Extensions
theme: jander

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/chronzerg/chronzerg.github.io.git
  branch: master
  message: Site update.