# Hexo Configuration

# Site
title: janderland
author: Jon Anderson

# URL
url: http://jander.land
root: /
permalink: :title/

# Directory
source_dir: source
public_dir: public
tag_dir: tags
code_dir: downloads/code

# Writing
post_asset_folder: false
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Extensions
theme: jander

# Deployment
deploy:
  type: git
  repo: https://github.com/chronzerg/chronzerg.github.io.git
  branch: master
  message: Site update.